BookSite/Areas/Admin/Controllers/UserController.cs
using Book.Database.Repository.IRepository;
using Book.Models;
using Book.Models.ViewModels;
using Book.Utilities;
using BookSite.Database;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace BookSite.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = StaticDetail.Role_Admin)] // Make sure only admins can access it
    public class UserController : Controller
    {
        private IUnitOfWork _unitOfWork;
        private UserManager<IdentityUser> _userManager { get; set; }
        private RoleManager<IdentityRole> _roleManager { get; set; }
        public UserController(IUnitOfWork unitOfWork,RoleManager<IdentityRole> roleManger, UserManager<IdentityUser> userManger) 
        { 
            _unitOfWork = unitOfWork;
            _userManager = userManger;
            _roleManager = roleManger;
        }

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult RoleManagement(string userId)
        {
            // Populate RoleManagementVM
            RoleManagementVM RoleVM = new RoleManagementVM()
            {
                ApplicationUser = _unitOfWork.ApplicationUserRepository.Get(u => u.Id == userId, includeProperties:"Company"),
                RoleList = _roleManager.Roles.Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Name
                }),
                CompanyList = _unitOfWork.CompanyRepository.GetAll().Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.CompanyId.ToString()
                }),

            };

            // Automatically retrieve and populate user role 
            RoleVM.ApplicationUser.Role = _userManager.GetRolesAsync(_unitOfWork.ApplicationUserRepository.Get(u=>u.Id == userId)).
                GetAwaiter().GetResult().FirstOrDefault();

            return View(RoleVM);
        }

        [HttpPost]
        public IActionResult RoleManagement(RoleManagementVM roleManagementVM)
        {
            // Retrieve old role
            string oldRole = _userManager.GetRolesAsync(_unitOfWork.ApplicationUserRepository.Get(u => u.Id == roleManagementVM.ApplicationUser.Id)).
                GetAwaiter().GetResult().FirstOrDefault();

            ApplicationUser applicationUser = _unitOfWork.ApplicationUserRepository.Get(u => u.Id == roleManagementVM.ApplicationUser.Id);

            // Check if the role is changed
            if (!(roleManagementVM.ApplicationUser.Role == oldRole))
            {

                // Check if the user is from a company, if so then assign one of the companies to the user
                if(roleManagementVM.ApplicationUser.Role == StaticDetail.Role_Company)
                {
                    applicationUser.CompanyId = roleManagementVM.ApplicationUser.CompanyId;
                }

                // If the old role is a company role, remove the company Id since its not a company user anymore
                if(oldRole == StaticDetail.Role_Company)
                {
                    applicationUser.CompanyId = null;
                }

                // Save Changes
                _unitOfWork.ApplicationUserRepository.Update(applicationUser);
                _unitOfWork.Save();

                // Remove Old role
                _userManager.RemoveFromRoleAsync(applicationUser, oldRole).GetAwaiter().GetResult();

                // Add new role
                _userManager.AddToRoleAsync(applicationUser, roleManagementVM.ApplicationUser.Role).GetAwaiter().GetResult();                         
            }
            // Check if only company is updated 
            else
            {
                if (oldRole == StaticDetail.Role_Company && applicationUser.CompanyId != roleManagementVM.ApplicationUser.CompanyId)
                {
                    applicationUser.CompanyId = roleManagementVM.ApplicationUser.CompanyId;
                    applicationUser.Name = roleManagementVM.ApplicationUser.Name;
                    applicationUser.PhoneNumber = roleManagementVM.ApplicationUser.PhoneNumber;
                    applicationUser.StreetAddress = roleManagementVM.ApplicationUser.StreetAddress;
                    applicationUser.City = roleManagementVM.ApplicationUser.City;
                    applicationUser.State = roleManagementVM.ApplicationUser.State;
                    applicationUser.PostalCode = roleManagementVM.ApplicationUser.PostalCode;
                    _unitOfWork.ApplicationUserRepository.Update(applicationUser);
                    _unitOfWork.Save();
                }
            }

            return RedirectToAction("Index");
        }

        #region API Calls
        [HttpGet]
        public IActionResult GetAll()
        {
            // Mapping tables
            List<ApplicationUser> users = _unitOfWork.ApplicationUserRepository.GetAll(includeProperties:"Company").ToList();


            foreach(var user in users)
            {
                
                user.Role = _userManager.GetRolesAsync(user).GetAwaiter().GetResult().FirstOrDefault();

                if(user.Company == null)
                {
                    user.Company = new()
                    {
                        Name = ""
                    };
                }
            }
            return Json(new {data = users});
        }

        [HttpPost]
        public IActionResult LockUnlock([FromBody]string id) // From body is from the database table
        {
            // Directly work with entity framework core
            var objFromDb = _unitOfWork.ApplicationUserRepository.Get(u => u.Id == id);
            if(objFromDb == null)
            {
                return Json(new { success = false, message = "Error While Locking/Unlocking" });
            }
            
            if(objFromDb.LockoutEnd != null && objFromDb.LockoutEnd> DateTime.Now)
            {
                // User is currently locked and needs to be unlocked
                objFromDb.LockoutEnd = DateTime.Now; // User will be unlocked
            }
            else
            {
                objFromDb.LockoutEnd = DateTime.Now.AddYears(1000);
            }

            _unitOfWork.ApplicationUserRepository.Update(objFromDb);
            _unitOfWork.Save();
            

            return Json(new { success = true, message = "Operation Sucecssful"});
        }
        #endregion

    }
}

BookSite/Controllers/CategoryController.cs
using Book.Models;
using BookSite.Database;
using Microsoft.AspNetCore.Mvc;

namespace BookSite.Controllers
{
    public class CategoryController : Controller
    {
        private ApplicationDbContext _db;
        public CategoryController(ApplicationDbContext db)
        {
            _db = db;
        }

        // Create Category 
        public IActionResult CategoryView()
        {
            IEnumerable<Category> objCategories = _db.Categories;
            return View(objCategories);
        }
        public IActionResult CreateCategory(Category cat)
        {
            if(cat.Name == cat.DisplayOder.ToString())
            {
                ModelState.AddModelError("name", "The Display Order cannot exactly match the Name");
            }
            if(ModelState.IsValid)
            {
                _db.Categories.Add(cat);
                _db.SaveChanges();
                TempData["success"] = "Category Created Successfully";
                return RedirectToAction("CategoryView");
            }
            return View();
        }

        // Edit Category 
        public IActionResult EditCategory(int? id)
        {
            if(id == null || id == 0)
            {
                return NotFound();
            }

            Category? categoryFromDb = _db.Categories.FirstOrDefault(u=>u.Id==id);
            if(categoryFromDb == null)
            {
                return NotFound();
            }
            return View(categoryFromDb);
        }
        [HttpPost]
        public IActionResult EditCategory(Category cat)
        {
            if (ModelState.IsValid)
            {
                _db.Categories.Update(cat);
                _db.SaveChanges();
                TempData["success"] = "Category Updated Successfully";
                return RedirectToAction("CategoryView");
            }
            return View();
        }

        // Edit Category 
        public IActionResult DeleteCategory(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            Category? categoryFromDb = _db.Categories.FirstOrDefault(u => u.Id == id);
            if (categoryFromDb == null)
            {
                return NotFound();
            }
            return View(categoryFromDb);
        }

        [HttpPost, ActionName("DeleteCategory")]
        public IActionResult SaveDeleteCategory(int? id)
        {
            Category? cat = _db.Categories.FirstOrDefault(c => c.Id==id);
            if(cat == null)
            {
                return NotFound();
            }
            _db.Categories.Remove(cat);
            _db.SaveChanges();
            TempData["success"] = "Category Deleted Successfully";
            return RedirectToAction("CategoryView");
        }
    }
}

BookSite/ViewComponents/ShoppingCartViewComponent.cs
using Book.Database.Repository.IRepository;
using Book.Utilities;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace BookSite.ViewComponents
{
    public class ShoppingCartViewComponent : ViewComponent
    {
        private readonly IUnitOfWork _unitOfWork;
        public ShoppingCartViewComponent(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier); // Populate userId
            if (userId != null)
            {
                if (HttpContext.Session.GetInt32(StaticDetail.SessionCart) == null)
                {
                    HttpContext.Session.SetInt32(StaticDetail.SessionCart,
                    _unitOfWork.ShoppingCartRepository.GetAll(u => u.ApplicationUserId == userId.Value).Count());
                }
                
                return View(HttpContext.Session.GetInt32(StaticDetail.SessionCart));
            }
            else
            {
                HttpContext.Session.Clear();
                return View(0);
            }
        }

    }
}

BookSite/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor httpContextAccessor

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookSite</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/BookSite.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />

    <!--Database API-->
    <link rel="stylesheet" href="//cdn.datatables.net/1.13.5/css/jquery.dataTables.min.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BookSite</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Customer" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Admin" asp-controller="Order" asp-action="Index">Manage Order</a>
                        </li>
                        <!--Check user role-->
                        @if(User.IsInRole(StaticDetail.Role_Admin))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="Identity" asp-page="/Account/Register">Create User</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="Admin" asp-controller="User" asp-action="Index">Users</a>
                            </li>
                            <!--Dropdown-->
                            <li>
                                <div class="nav-item dropdown">
                                    <button class="nav-link dropdown-toggle" type="button" data-bs-toggle="dropdown">
                                        Content Management
                                    </button>
                                    <div class="dropdown-menu">
                                        <ul class="m-0 p-0" style="list-style:none;">
                                            <li><a asp-area="Admin" asp-controller="Category" asp-action="CategoryView" class="dropdown-item">Category</a></li>
                                            <li><a asp-area="Admin" asp-controller="Product" asp-action="ViewProduct" class="dropdown-item">Product</a></li>
                                            <li><a asp-area="Admin" asp-controller="Company" asp-action="ViewCompany" class="dropdown-item">Company</a></li>                                           
                                        </ul>
                                    </div>
                                </div>
                            </li>
                        }
                        
                            <li class="nav-item">
                                <a class="nav-link" asp-area="Customer" asp-controller="Cart" asp-action="ViewCart">
                                    @await Component.InvokeAsync("ShoppingCart")
                                </a>
                            </li>
                        

                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - BookSite - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <!--Database API-->
    <script src="https://cdn.datatables.net/1.13.5/js/jquery.dataTables.min.js"></script>
    <!--Sweet Alert-->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <!--Rich Text Editor-->
    <script src="https://cdn.tiny.cloud/1/shwfri1auffffej06ejph94684e40vcid350n7d5y1zt1vy2/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BookSite/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <h2>@TempData["success"]</h2>
}
@if (TempData["error"] != null)
{
    <h2>@TempData["error"]</h2>
}